version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    restart: always
    environment:
      SA_PASSWORD: "Your_password123" # /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_password123' -C -Q "SELECT name FROM sys.databases"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: